steps:
  # Step 1: Build the Docker image for the backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ajfs-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ajfs-backend:latest'
      - '.'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ajfs-backend:$COMMIT_SHA'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ajfs-backend:latest'

  # Step 4: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ajfs-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ajfs-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'EMAIL_HOST=${_EMAIL_HOST},EMAIL_PORT=${_EMAIL_PORT},EMAIL_SECURE=${_EMAIL_SECURE},EMAIL_USER=${_EMAIL_USER},EMAIL_PASS=${_EMAIL_PASS},CONTACT_RECEIVER_EMAIL=${_CONTACT_RECEIVER_EMAIL},FRONTEND_URL=${_FRONTEND_URL},NODE_ENV=production'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60'

# Substitution variables - IMPORTANT: Set these in Cloud Build trigger settings
# DO NOT commit actual values to version control
substitutions:
  _EMAIL_HOST: 'smtp.hostinger.com'
  _EMAIL_PORT: '465'
  _EMAIL_SECURE: 'true'
  _EMAIL_USER: 'your_email@ajfsindia.com'  # CHANGE THIS
  _EMAIL_PASS: 'your_password'  # CHANGE THIS - Use Secret Manager in production
  _CONTACT_RECEIVER_EMAIL: 'admin@ajfsindia.com'  # CHANGE THIS
  _FRONTEND_URL: 'https://www.ajfsindia.com'  # CHANGE THIS after frontend deployment

# Images to be stored in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ajfs-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ajfs-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
